изварягвгреки:
  type: article
  author: Петрухин, В. Я.
  title: "«Из варяг в греки»: начало исторического пути России"
  parent:
    title: "Славянский альманах"
    issue: 1996
  date: 1997
  url: https://cyberleninka.ru/article/n/iz-varyag-v-greki-nachalo-istoricheskogo-puti-rossii

крещение:
  type: article
  author:
    - Максимова, Е. Р.
    - Муканалиева, А. Р.
  title: "Крещение Руси"
  parent:
    title: "Бюллетень медицинских Интернет-конференций"
    volume: 5
    issue: 12
    issn: "2224-6150"
  date: 2015
  page: "1571"
  url: https://cyberleninka.ru/article/n/kreschenie-rusi

великоепосольство:
  type: article
  author: Гольцева, Татьяна Николаевна
  title: "«Великое посольство» 1697–1698 гг. как опыт личного восприятия Петром I западноевропейской архитектуры"
  parent:
    title: "Architecture and Modern Information Technologies"
    volume: 60
    issue: 3
  date: 2022
  page: "40-64"
  doi: 10.24412/1998-4839-2022-3-40-64
  url: https://cyberleninka.ru/article/n/velikoe-posolstvo-1697-1698-gg-kak-opyt-lichnogo-vospriyatiya-petrom-i-zapadnoevropeyskoy-arhitektury

реформыпетра1:
  type: article
  author:
    - Калашникова, Е. Б.
    - Горшкова, Н. Д.
  title: "Реформы Петра I: содержание и их влияние на развитие России"
  parent:
    title: "Международный журнал гуманитарных и естественных наук"
    issue: 11-3
  date: 2021
  page: "97-100"
  doi: 10.24411/2500-1000-2021-1135
  url: https://cyberleninka.ru/article/n/reformy-petra-i-soderzhanie-i-ih-vliyanie-na-razvitie-rossii

венскийконгресс:
  type: article
  author:
    - Хазин, А. Л.
    - Богданов, С. В.
  title: "Венский конгресс 1814–1815 годов и его участники: коммуникативные инструменты, ошибки, достижения"
  parent:
    title: "Государственное управление. Электронный вестник"
    issue: 40
  date: 2013-10
  url: https://cyberleninka.ru/article/n/venskiy-kongress-1814-1815-godov-i-ego-uchastniki-kommunikativnye-instrumenty-oshibki-dostizheniya

ссср:
  type: article
  author: Еремин, Андрей Геннадьевич
  title: "Участие СССР в переделе сфер влияния в период формирования биполярной системы международных отношений (1945–1964 гг.)"
  parent:
    title: "Историческая и социально-образовательная мысль"
    volume: 11
    issue: 1
  date: 2012
  url: https://cyberleninka.ru/article/n/uchastie-sssr-v-peredele-sfer-vliyaniya-v-period-formirovaniya-bipolyarnoy-sistemy-mezhdunarodnyh-otnosheniy-1945-1964-gg
