name: Compile and Deploy Typst

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  typst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: git lfs pull
      - uses: hustcer/setup-nu@v3
      - uses: typst-community/setup-typst@v5
      - uses: typstyle-rs/typstyle-action@v1.0.1
      - uses: stefanzweifel/git-auto-commit-action@v7
      - name: install fonts
        run: |
          wget https://download.gnu.org.ua/release/newcm/newcm-8.1.1.txz
          mkdir --parents ~/.local/share/fonts/ncm
          tar --extract --file newcm-8.1.1.txz --directory="$HOME/.local/share/fonts/ncm"
      - run: .github/workflows/compile_typst.nu
        env:
          MAX_AGE: "45day"
          PDFS: "_site"
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
